---

- hosts: all
  become: true
  tasks:

  - name: Enable a RHSM repository
    rhsm_repository:
      name: rhel-8-for-x86_64-appstream-rpms

  - name: Enable a RHSM repository
    rhsm_repository:
      name: rhel-8-for-x86_64-baseos-rpms

  - name: disable a RHSM repository
    rhsm_repository:
      name: codeready-builder-for-rhel-8-x86_64-rpms
      state: enabled
