---

- hosts: all
  become: true
  tasks:

  - name: Update Repo index
    dnf:
      update_cache: yes

  - name: install apache2 and PHP package
    dnf:
      name: 
        - httpd
        - php
      state: latest
