---

- hosts: all
  become: true
  tasks:

  - name: install apache and PHP package for RHEL
    dnf:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"

