---

- hosts: all
  become: true
  tasks:

   - name: install apache2 and PHP package for RHEL
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansisble_distribution == "RedHat"

