---
 
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (RedHat)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb for Ubuntu servers
    apt:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb for RedHat servers
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "RedHat"

