---

- name: copy
  hosts: "workstations"
  become: true
  collections:
  #   - ansible.windows
  #   - community.windows

  tasks:
    - name: Fetch file from remote Linux host to control node
      fetch:
        src: /plex/Library/movies/resmovies.txt
        dest: /tmp/{{ inventory_hostname }}/  # Temporary location on control node
        flat: yes
    
    - name: Copy fetched file from control node to Windows host
      become: false
      ansible.windows.win_copy:
        src: /tmp/{{ inventory_hostname }}/resmovies.txt # Path on the control node
        dest: E:\resmovies.txt
      delegate_to: myIP

